//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string Semester { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeEngName { get; set; }
        public string EmployeePic { get; set; }
        public string IDCard { get; set; }
        public string Sex { get; set; }
        public string Birthday { get; set; }
        public string BornLoc { get; set; }
        public string RegisterLoc { get; set; }
        public string NowCondition { get; set; }
        public string AlwaysTel { get; set; }
        public string AlwaysAddress { get; set; }
        public string NowTel { get; set; }
        public string NowTelMark { get; set; }
        public string NowAddress { get; set; }
        public string NowAddressMark { get; set; }
        public string MobilePhone { get; set; }
        public string MobilePhoneMark { get; set; }
        public string Marriage { get; set; }
        public string UnitCode { get; set; }
        public string Nationality { get; set; }
        public string ArriveDate { get; set; }
        public string TitleName { get; set; }
        public string SalaryTitle { get; set; }
        public string HighestSch { get; set; }
        public string SecondJobs { get; set; }
        public string Account { get; set; }
        public string Email { get; set; }
        public string EmailMark { get; set; }
        public string WWW { get; set; }
        public string WWWMark { get; set; }
        public string OfficeNo { get; set; }
        public string OfficeNoMark { get; set; }
        public string OfficeTel { get; set; }
        public string OfficeTelMark { get; set; }
        public string OfficeHour { get; set; }
        public string UrgentName { get; set; }
        public string UrgentTel { get; set; }
        public string Password { get; set; }
        public string CreateDateTime { get; set; }
        public string CIDCard { get; set; }
        public string Note { get; set; }
        public string Deans_no { get; set; }
        public string Lib_no { get; set; }
        public string People_no { get; set; }
        public string FullMark { get; set; }
        public string StopMark { get; set; }
        public string pos_goverment { get; set; }
        public string position { get; set; }
        public string disoclock { get; set; }
        public string Ntust_Email { get; set; }
        public byte[] EryPwd { get; set; }
        public byte[] EryID { get; set; }
        public string LookCheck { get; set; }
        public string PDProtect_mark { get; set; }
    }
}
